### ISSUE TITLE
Lizenz des Projekts ist noch nicht angegeben

### ISSUE THREAD

**Issue by tanius** [Stryi/Vorratsuebersicht#4]
Die Datei [Licenses.html](https://github.com/Stryi/Vorratsuebersicht/blob/master/Licenses.html) informiert über die Lizenzen verwendeter Open Source Komponenten. Allerdings fehlt noch eine Angabe, unter welcher Lizenz das Projekt selbst steht. Wenn ein anderer Entwickler gerne Teile dieser Anwendung wiederverwenden möchte, ist also bisher nicht klar ob und unter welcher Lizenz das möglich ist.

Es ist dabei empfehlenswert, in einer Datei `LICENSE.txt` oder `LICENSE.md` nur den Text der Lizenz zu veröffentlichen. Github kann dies dann automatisch erkennen und in den Metadatan des Repositories anzeigen ([siehe](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)).

**Comment by Stryi** [comment]
Hi! Habe gerade die Nachricht entdeckt. Ich kenne mich da gar nicht gut aus. Gibt es eine Lizenz, dass jeder den Quellcode wiederverwenden kann und eigene Apps erstellen kann, aber der Name "Vorratsübersicht" nur mir vorbehalten bleibt?

**Comment by tanius** [comment]
Dies (Quellcode-Lizenz und Namensnutzung) sind zwei verschiedene Dinge. Eine Open-Source-Lizenz erlaubt anderen, den Quellcode unter bestimmten Bedingungen wiederzuverwenden. Eine Marke (en: Trademark) regelt, wer den Namen in welcher Form verwenden kann. Zitat von einer Organisation, die sich mit Open-Source-Lizenzen beschäftigt:

> **Does Open Source mean anybody else can use my name and logo?**
> 
> No, at least not any more than they could otherwise. Open Source is about software source code, not about identity. That is, letting people use your code under an Open Source license is not the same as letting them use your trademarks or other identifying attributes, except insofar as they would be permitted to anyway (for example, in nominative use doctrine). There are many companies and other organizations that release open source code while exercising tight control over their trademarks.
> 
> Trademarks and other marks of attribution are primarily about preventing public confusion over identity and provenance, and therefore trademark regulation is useful in Open Source software in the same way it is useful generally.
> 
> ([Quelle](http://opensource.org/faq#copying-and-identity))

Um also zu verhindern, dass andere für ihre eigenen Projekte (von Deinem abgeleitet oder nicht, das wäre egal) den Namen "Vorratsübersicht" verwenden, müsstest Du eine Marke dafür haben. In manchen Ländern ist das automatisch der Fall, wenn man eine Bezeichnung konsistent für ein eigenes Produkt verwendet. In Deutschland ist das leider nicht so:

> Proprietary rights in relation to a trademark may be established through actual use of that trademark in the marketplace or through registration […]. In some jurisdictions, trademark rights can be established through either or both means. […] Some countries, such as Germany, offer a limited amount of common law rights for unregistered marks where to gain protection, the goods or services must first occupy a highly significant position in the marketplace — where this could be 40% or more market share for sales in the particular class of goods or services. ([source](https://en.wikipedia.org/wiki/Trademark#Registration))

Du müsstest also eine Marke anmelden. Für Deutschland kostet das ca. 300 EUR ([Quelle](https://www.ra-plutte.de/was-kostet-eine-markenanmeldung-strategie-tipps-beispiele/#DPMA)). Das Problem wäre dabei allerdings, dass "Vorratsübersicht" vermutlich nicht als Wortmarke akzeptiert würde, weil es ein normales deutsches Wort ist, kein Name.

Zusammengefasst: Für den Quelltext kannst Du irgendeine Open Source Lizenz aussuchen. An der Art ob und wie der Name Deiner Anwendung wiederverwendet werden darf, ändert das nichts. Die Apache 2.0 Lizenz ist hier nützlich, weil sie diese Unterscheidung bereits in der Lizenz deutlich macht:

> Trademarks. This License does not grant permission to use the trade names, trademarks, service marks, or product names of the Licensor, except as required for reasonable and customary use in describing the origin of the Work and reproducing the content of the NOTICE file. ([source](http://www.apache.org/licenses/LICENSE-2.0.html#trademarks))

**Comment by Stryi** [comment]
Ich habe jetzt die gleiche Lizenz eingetragen, wie meine Komponenten auch haben.

Ich kann mich erinnern, gehört zu haben, dass es Lizenzen gibt, wenn man deren Komponenten benutzt, dann darf daraus resultierendes Produkt keine schlechtere Lizenz haben. Somit meine ich, auf der sicheren Seite zu sein.
