### ISSUE TITLE
sync mit Syncthing macht Probleme

### ISSUE THREAD

**Issue by albialbi** [Stryi/Vorratsuebersicht#7]
Leider werden beim Sync mit syncthing oft sync Konflikte erzeugt.
Wäre es möglich, das VÜ selber einen Abgleich zwischen 2 DBs vornehmen könnte um den Konflikt zu lösen?

**Comment by Stryi** [comment]
Konflikte bei Datei basierten Datenbanken auf Dateiebene zu lösen ist unmöglich.
